-- ============================================================
-- V15__more_dishes.sql
-- 扩充 10 道真实家常菜 + 21 个新食材
-- 营养值参考《中国食物成分表》；菜谱来源：下厨房真实菜谱 + GitHub Anduin2017/HowToCook（MIT）
-- 幂等：重复执行不会产生重复数据（先 DELETE by name 再 INSERT）
-- ============================================================

-- 删除已有菜品关联数据（幂等）
DELETE FROM dish_step      WHERE dish_id IN (SELECT id FROM dish WHERE name IN ('红烧肉','宫保鸡丁','麻婆豆腐','糖醋排骨','可乐鸡翅','鱼香肉丝','清蒸鲈鱼','西红柿鸡蛋汤','紫菜蛋花汤','虎皮青椒'));
DELETE FROM dish_dict      WHERE dish_id IN (SELECT id FROM dish WHERE name IN ('红烧肉','宫保鸡丁','麻婆豆腐','糖醋排骨','可乐鸡翅','鱼香肉丝','清蒸鲈鱼','西红柿鸡蛋汤','紫菜蛋花汤','虎皮青椒'));
DELETE FROM dish_ingredient WHERE dish_id IN (SELECT id FROM dish WHERE name IN ('红烧肉','宫保鸡丁','麻婆豆腐','糖醋排骨','可乐鸡翅','鱼香肉丝','清蒸鲈鱼','西红柿鸡蛋汤','紫菜蛋花汤','虎皮青椒'));
DELETE FROM dish           WHERE name IN ('红烧肉','宫保鸡丁','麻婆豆腐','糖醋排骨','可乐鸡翅','鱼香肉丝','清蒸鲈鱼','西红柿鸡蛋汤','紫菜蛋花汤','虎皮青椒');

-- 删除已有新食材及营养（幂等，先删营养再删食材）
DELETE FROM ingredient_nutrition WHERE ingredient_id IN (SELECT id FROM ingredient WHERE name IN ('五花肉','排骨','鸡翅','花生','鲈鱼','茄子','紫菜(干)','木耳(干)','豆腐(嫩)','大葱','生姜','大蒜','酱油(生抽)','酱油(老抽)','醋','料酒','豆瓣酱','淀粉','冰糖','蚝油','可乐'));
DELETE FROM ingredient           WHERE name IN ('五花肉','排骨','鸡翅','花生','鲈鱼','茄子','紫菜(干)','木耳(干)','豆腐(嫩)','大葱','生姜','大蒜','酱油(生抽)','酱油(老抽)','醋','料酒','豆瓣酱','淀粉','冰糖','蚝油','可乐');

-- ============ 新增食材（21个） ============
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('五花肉',20,0.03,25,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('排骨',20,0.045,25,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('鸡翅',20,0.03,25,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('花生',20,0.02,30,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('鲈鱼',20,0.04,26,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('茄子',20,0.008,24,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('紫菜(干)',20,0.15,24,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('木耳(干)',20,0.08,24,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('豆腐(嫩)',20,0.006,28,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('大葱',20,0.008,30,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('生姜',20,0.012,30,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('大蒜',20,0.01,30,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('酱油(生抽)',21,0.015,30,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('酱油(老抽)',21,0.015,30,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('醋',21,0.012,30,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('料酒',21,0.015,30,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('豆瓣酱',20,0.025,30,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('淀粉',20,0.01,30,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('冰糖',20,0.012,30,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('蚝油',21,0.018,30,0,0,0);
INSERT INTO ingredient(name,unit_id,price,purchase_category_id,purchase_count,usage_count,deleted) VALUES ('可乐',21,0.006,30,0,0,0);

-- ============ 食材营养 EAV（每食材6项：1cal 2protein 3fat 4carb 5sugar 6gi） ============
-- 每食材6条独立 INSERT...SELECT，避免 MySQL 多值 SELECT 语法问题
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,518 FROM ingredient WHERE name='五花肉';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,7.7 FROM ingredient WHERE name='五花肉';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,55.0 FROM ingredient WHERE name='五花肉';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,2.4 FROM ingredient WHERE name='五花肉';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,0 FROM ingredient WHERE name='五花肉';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='五花肉';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,278 FROM ingredient WHERE name='排骨';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,18.3 FROM ingredient WHERE name='排骨';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,22.0 FROM ingredient WHERE name='排骨';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,1.7 FROM ingredient WHERE name='排骨';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,0 FROM ingredient WHERE name='排骨';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='排骨';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,194 FROM ingredient WHERE name='鸡翅';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,17.4 FROM ingredient WHERE name='鸡翅';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,14.0 FROM ingredient WHERE name='鸡翅';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,1.3 FROM ingredient WHERE name='鸡翅';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,0.2 FROM ingredient WHERE name='鸡翅';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='鸡翅';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,589 FROM ingredient WHERE name='花生';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,24.4 FROM ingredient WHERE name='花生';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,50.0 FROM ingredient WHERE name='花生';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,16.2 FROM ingredient WHERE name='花生';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,0 FROM ingredient WHERE name='花生';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='花生';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,105 FROM ingredient WHERE name='鲈鱼';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,18.6 FROM ingredient WHERE name='鲈鱼';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,3.4 FROM ingredient WHERE name='鲈鱼';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,0 FROM ingredient WHERE name='鲈鱼';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,0 FROM ingredient WHERE name='鲈鱼';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='鲈鱼';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,23 FROM ingredient WHERE name='茄子';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,1.0 FROM ingredient WHERE name='茄子';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,0.2 FROM ingredient WHERE name='茄子';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,4.9 FROM ingredient WHERE name='茄子';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,3.2 FROM ingredient WHERE name='茄子';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,15 FROM ingredient WHERE name='茄子';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,207 FROM ingredient WHERE name='紫菜(干)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,26.7 FROM ingredient WHERE name='紫菜(干)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,1.1 FROM ingredient WHERE name='紫菜(干)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,44.1 FROM ingredient WHERE name='紫菜(干)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,0 FROM ingredient WHERE name='紫菜(干)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='紫菜(干)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,205 FROM ingredient WHERE name='木耳(干)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,12.1 FROM ingredient WHERE name='木耳(干)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,1.5 FROM ingredient WHERE name='木耳(干)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,65.6 FROM ingredient WHERE name='木耳(干)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,0 FROM ingredient WHERE name='木耳(干)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='木耳(干)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,50 FROM ingredient WHERE name='豆腐(嫩)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,5.7 FROM ingredient WHERE name='豆腐(嫩)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,2.6 FROM ingredient WHERE name='豆腐(嫩)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,1.8 FROM ingredient WHERE name='豆腐(嫩)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,0.6 FROM ingredient WHERE name='豆腐(嫩)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,15 FROM ingredient WHERE name='豆腐(嫩)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,33 FROM ingredient WHERE name='大葱';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,1.7 FROM ingredient WHERE name='大葱';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,0.3 FROM ingredient WHERE name='大葱';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,6.5 FROM ingredient WHERE name='大葱';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,3.2 FROM ingredient WHERE name='大葱';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,15 FROM ingredient WHERE name='大葱';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,41 FROM ingredient WHERE name='生姜';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,1.3 FROM ingredient WHERE name='生姜';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,0.6 FROM ingredient WHERE name='生姜';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,7.6 FROM ingredient WHERE name='生姜';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,1.4 FROM ingredient WHERE name='生姜';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='生姜';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,149 FROM ingredient WHERE name='大蒜';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,6.6 FROM ingredient WHERE name='大蒜';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,0.6 FROM ingredient WHERE name='大蒜';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,28.8 FROM ingredient WHERE name='大蒜';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,3.2 FROM ingredient WHERE name='大蒜';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='大蒜';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,63 FROM ingredient WHERE name='酱油(生抽)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,5.6 FROM ingredient WHERE name='酱油(生抽)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,0.1 FROM ingredient WHERE name='酱油(生抽)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,10.1 FROM ingredient WHERE name='酱油(生抽)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,1.2 FROM ingredient WHERE name='酱油(生抽)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='酱油(生抽)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,75 FROM ingredient WHERE name='酱油(老抽)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,6.0 FROM ingredient WHERE name='酱油(老抽)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,0.1 FROM ingredient WHERE name='酱油(老抽)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,13.0 FROM ingredient WHERE name='酱油(老抽)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,2.0 FROM ingredient WHERE name='酱油(老抽)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='酱油(老抽)';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,31 FROM ingredient WHERE name='醋';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,2.1 FROM ingredient WHERE name='醋';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,0.3 FROM ingredient WHERE name='醋';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,4.9 FROM ingredient WHERE name='醋';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,1.2 FROM ingredient WHERE name='醋';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,5 FROM ingredient WHERE name='醋';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,80 FROM ingredient WHERE name='料酒';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,0.3 FROM ingredient WHERE name='料酒';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,0 FROM ingredient WHERE name='料酒';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,4.2 FROM ingredient WHERE name='料酒';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,1.0 FROM ingredient WHERE name='料酒';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='料酒';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,178 FROM ingredient WHERE name='豆瓣酱';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,8.5 FROM ingredient WHERE name='豆瓣酱';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,6.8 FROM ingredient WHERE name='豆瓣酱';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,18.4 FROM ingredient WHERE name='豆瓣酱';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,3.2 FROM ingredient WHERE name='豆瓣酱';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='豆瓣酱';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,381 FROM ingredient WHERE name='淀粉';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,0.2 FROM ingredient WHERE name='淀粉';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,0.1 FROM ingredient WHERE name='淀粉';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,92.5 FROM ingredient WHERE name='淀粉';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,0 FROM ingredient WHERE name='淀粉';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='淀粉';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,397 FROM ingredient WHERE name='冰糖';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,0.1 FROM ingredient WHERE name='冰糖';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,0 FROM ingredient WHERE name='冰糖';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,98.5 FROM ingredient WHERE name='冰糖';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,98.5 FROM ingredient WHERE name='冰糖';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='冰糖';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,51 FROM ingredient WHERE name='蚝油';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,2.9 FROM ingredient WHERE name='蚝油';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,0.3 FROM ingredient WHERE name='蚝油';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,9.7 FROM ingredient WHERE name='蚝油';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,7.0 FROM ingredient WHERE name='蚝油';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='蚝油';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,1,43 FROM ingredient WHERE name='可乐';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,2,0 FROM ingredient WHERE name='可乐';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,3,0 FROM ingredient WHERE name='可乐';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,4,10.6 FROM ingredient WHERE name='可乐';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,5,10.6 FROM ingredient WHERE name='可乐';
INSERT INTO ingredient_nutrition(ingredient_id,metric_id,value) SELECT id,6,0 FROM ingredient WHERE name='可乐';

-- ============ 新增菜品（10道） ============
INSERT INTO dish(name,note,prep_time,cook_time,difficulty,deleted) VALUES ('红烧肉','经典家常红烧肉，色泽红亮、肥而不腻，肥瘦相间的五花肉入口即化。',20,60,3,0);
INSERT INTO dish(name,note,prep_time,cook_time,difficulty,deleted) VALUES ('宫保鸡丁','川味经典，糊辣荔枝味，鸡丁滑嫩、花生酥脆，咸甜酸辣兼备。',30,15,4,0);
INSERT INTO dish(name,note,prep_time,cook_time,difficulty,deleted) VALUES ('麻婆豆腐','川菜代表，麻、辣、烫、香、酥、嫩、鲜、活，豆腐滑嫩入味，下饭一绝。',15,20,3,0);
INSERT INTO dish(name,note,prep_time,cook_time,difficulty,deleted) VALUES ('糖醋排骨','酸甜可口、外酥里嫩，色泽红亮，是老少皆宜的经典家常菜。',15,45,4,0);
INSERT INTO dish(name,note,prep_time,cook_time,difficulty,deleted) VALUES ('可乐鸡翅','色泽红亮、咸甜适口、肉质嫩滑，做法简单的家常创意菜。',10,30,3,0);
INSERT INTO dish(name,note,prep_time,cook_time,difficulty,deleted) VALUES ('鱼香肉丝','经典川菜，酸甜微辣、咸鲜下饭，鱼香汁糖醋比例是灵魂。',20,10,4,0);
INSERT INTO dish(name,note,prep_time,cook_time,difficulty,deleted) VALUES ('清蒸鲈鱼','粤式清蒸，鱼肉细嫩鲜美，最大限度保留鲈鱼原味，清淡营养。',15,15,2,0);
INSERT INTO dish(name,note,prep_time,cook_time,difficulty,deleted) VALUES ('西红柿鸡蛋汤','酸甜开胃、快手省时的家常汤品，老少皆宜。',5,10,1,0);
INSERT INTO dish(name,note,prep_time,cook_time,difficulty,deleted) VALUES ('紫菜蛋花汤','清淡鲜美的快手汤，紫菜富含碘和钙，搭配鸡蛋营养均衡。',5,10,1,0);
INSERT INTO dish(name,note,prep_time,cook_time,difficulty,deleted) VALUES ('虎皮青椒','外皮微焦起皱、咸鲜透着酸甜的开胃下饭菜，操作简单。',5,10,2,0);

-- ============ 菜品步骤 ============
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,1,'五花肉切3cm见方块，冷水下锅加料酒、葱段、姜片焯水5分钟去血沫，捞出温水洗净沥干',NULL,1 FROM dish WHERE name='红烧肉';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,2,'锅中小火加少许油，放入冰糖15g不断翻炒至融化成琥珀色糖色',NULL,2 FROM dish WHERE name='红烧肉';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,3,'迅速放入五花肉翻炒，使每块肉均匀裹上糖色',NULL,3 FROM dish WHERE name='红烧肉';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,4,'加入生抽、老抽、料酒翻炒上色出香',NULL,4 FROM dish WHERE name='红烧肉';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,5,'倒入热水没过肉块，放入姜片葱段，大火烧开后转小火加盖炖约50分钟至肉酥烂',NULL,5 FROM dish WHERE name='红烧肉';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,6,'开盖大火收汁至浓稠，加盐调味，翻炒均匀出锅',NULL,6 FROM dish WHERE name='红烧肉';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,1,'鸡胸肉切1.5cm见方的丁，加少许盐、生抽、料酒、淀粉抓匀腌制20分钟',NULL,1 FROM dish WHERE name='宫保鸡丁';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,2,'花生米用小火焙香或油炸至酥脆备用；大葱切1.5cm颗粒，姜蒜切末',NULL,2 FROM dish WHERE name='宫保鸡丁';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,3,'调碗芡：生抽20ml、醋15ml、白糖10g、淀粉5g、清水30ml混合搅匀',NULL,3 FROM dish WHERE name='宫保鸡丁';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,4,'热锅冷油，油温五成热下鸡丁滑炒至变白断生，盛出备用',NULL,4 FROM dish WHERE name='宫保鸡丁';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,5,'锅留底油，爆香姜蒜末，下大葱粒、青椒丁、花生快速翻炒',NULL,5 FROM dish WHERE name='宫保鸡丁';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,6,'倒回鸡丁，搅匀的碗芡沿锅边淋入，大火快速翻炒收汁裹匀出锅',NULL,6 FROM dish WHERE name='宫保鸡丁';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,1,'嫩豆腐切2cm见方块，放入加了少许盐的开水中焯烫2分钟，捞出沥干',NULL,1 FROM dish WHERE name='麻婆豆腐';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,2,'猪肉剁成肉末；姜蒜切末备用',NULL,2 FROM dish WHERE name='麻婆豆腐';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,3,'热锅凉油，下肉末煸炒至变色出油，盛出备用',NULL,3 FROM dish WHERE name='麻婆豆腐';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,4,'锅留底油，小火下豆瓣酱炒出红油，加入姜蒜末爆香',NULL,4 FROM dish WHERE name='麻婆豆腐';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,5,'加入适量清水或高汤烧开，放入豆腐块，加生抽调味，中小火煮3分钟入味',NULL,5 FROM dish WHERE name='麻婆豆腐';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,6,'放入肉末，分次淋入水淀粉勾薄芡，轻轻推动至汤汁浓稠裹住豆腐，出锅',NULL,6 FROM dish WHERE name='麻婆豆腐';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,1,'排骨剁小段，冷水下锅加料酒、姜片焯水5分钟，撇去浮沫，温水洗净沥干',NULL,1 FROM dish WHERE name='糖醋排骨';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,2,'排骨表面薄薄拍一层干淀粉，油温170度下锅炸3-5分钟至金黄酥脆，捞出控油',NULL,2 FROM dish WHERE name='糖醋排骨';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,3,'锅洗净加少量热水，放入白糖40g小火熬煮，轻轻搅拌至糖完全溶解呈淡黄色',NULL,3 FROM dish WHERE name='糖醋排骨';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,4,'倒入炸好的排骨迅速翻炒上色，依次加入香醋、生抽、老抽翻炒均匀',NULL,4 FROM dish WHERE name='糖醋排骨';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,5,'加入开水至刚好没过排骨，大火烧开后转小火焖煮20分钟入味',NULL,5 FROM dish WHERE name='糖醋排骨';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,6,'转大火收汁，不断翻炒至汤汁浓稠均匀挂在排骨上，出锅装盘',NULL,6 FROM dish WHERE name='糖醋排骨';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,1,'鸡翅洗净，两面各划两刀便于入味；冷水下锅加料酒、姜片煮开焯水2分钟，捞出洗净',NULL,1 FROM dish WHERE name='可乐鸡翅';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,2,'用生抽10ml将鸡翅腌制10分钟，使其入味',NULL,2 FROM dish WHERE name='可乐鸡翅';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,3,'锅小火放少许油，下姜片爆香，放入鸡翅煎至两面金黄',NULL,3 FROM dish WHERE name='可乐鸡翅';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,4,'倒入可乐300ml（约一听）没过鸡翅，加入生抽、老抽、白糖、食盐调味',NULL,4 FROM dish WHERE name='可乐鸡翅';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,5,'大火烧开后转中火慢煮约15分钟，使鸡翅熟透入味',NULL,5 FROM dish WHERE name='可乐鸡翅';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,6,'转大火收汁，至可乐呈现浓稠挂丝状态，关火装盘',NULL,6 FROM dish WHERE name='可乐鸡翅';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,1,'猪肉顺纹切丝，加盐、料酒、少许蛋清、淀粉抓匀腌制15分钟',NULL,1 FROM dish WHERE name='鱼香肉丝';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,2,'木耳提前泡发撕成小块，胡萝卜、青椒分别切丝，葱姜蒜切末',NULL,2 FROM dish WHERE name='鱼香肉丝';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,3,'调鱼香汁：醋15ml、白糖15g、生抽10ml、盐少许、淀粉5g、清水30ml混合（糖醋约1:1）',NULL,3 FROM dish WHERE name='鱼香肉丝';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,4,'热锅多放些油，五成热下肉丝快速滑散至变白，盛出备用',NULL,4 FROM dish WHERE name='鱼香肉丝';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,5,'锅留底油，小火炒豆瓣酱出红油，加葱姜蒜末爆香，下胡萝卜丝、木耳、青椒丝大火翻炒断生',NULL,5 FROM dish WHERE name='鱼香肉丝';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,6,'倒回肉丝，搅匀鱼香汁淋入，大火快速翻炒收汁裹匀，出锅',NULL,6 FROM dish WHERE name='鱼香肉丝';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,1,'鲈鱼处理干净洗净，用厨房纸擦干水分，两面各划几刀；用盐和料酒抹遍鱼身内外腌制10分钟',NULL,1 FROM dish WHERE name='清蒸鲈鱼';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,2,'姜一半切片一半切丝，大葱葱白切段、葱绿切丝，葱丝泡冷水备用',NULL,2 FROM dish WHERE name='清蒸鲈鱼';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,3,'蒸盘用筷子架空，鱼肚内塞入葱段姜片，鱼身铺上姜片葱白',NULL,3 FROM dish WHERE name='清蒸鲈鱼';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,4,'蒸锅水烧开，大火放入鲈鱼蒸8-10分钟（视鱼大小），关火虚蒸2分钟',NULL,4 FROM dish WHERE name='清蒸鲈鱼';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,5,'取出倒掉盘中蒸汁（去腥），去掉鱼身葱姜，重新铺上葱丝姜丝',NULL,5 FROM dish WHERE name='清蒸鲈鱼';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,6,'淋上蒸鱼豉油（生抽），另锅烧热食用油15ml，浇淋在葱姜丝上激出香味即成',NULL,6 FROM dish WHERE name='清蒸鲈鱼';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,1,'番茄洗净切小块；鸡蛋打入碗中充分打散；葱切花',NULL,1 FROM dish WHERE name='西红柿鸡蛋汤';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,2,'锅中放油，烧热后下葱花爆香，放入番茄块翻炒至出汁软烂',NULL,2 FROM dish WHERE name='西红柿鸡蛋汤';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,3,'加入适量清水（约800ml），大火烧开',NULL,3 FROM dish WHERE name='西红柿鸡蛋汤';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,4,'水沸后转小火，将蛋液沿锅边缓缓淋入，形成蛋花',NULL,4 FROM dish WHERE name='西红柿鸡蛋汤';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,5,'待蛋花浮起，加盐调味，淋几滴香油，撒葱花出锅',NULL,5 FROM dish WHERE name='西红柿鸡蛋汤';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,1,'干紫菜用清水浸泡10分钟，洗净沙粒，捞出沥干；鸡蛋打散；葱切花',NULL,1 FROM dish WHERE name='紫菜蛋花汤';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,2,'锅中加入约1升清水，大火烧开',NULL,2 FROM dish WHERE name='紫菜蛋花汤';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,3,'水开后放入紫菜，转中火煮2分钟',NULL,3 FROM dish WHERE name='紫菜蛋花汤';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,4,'转小火，将蛋液沿筷子缓缓倒入沸水旋涡处，形成飘逸蛋花',NULL,4 FROM dish WHERE name='紫菜蛋花汤';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,5,'加盐调味，撒入葱花，淋少许食用油或香油，关火出锅',NULL,5 FROM dish WHERE name='紫菜蛋花汤';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,1,'青椒去蒂去籽洗净，纵向剖开成片；大蒜切末',NULL,1 FROM dish WHERE name='虎皮青椒';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,2,'调汁：生抽15ml、醋15ml、白糖15g、盐3g混合搅匀',NULL,2 FROM dish WHERE name='虎皮青椒';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,3,'锅烧热放油20ml，五成热将青椒片单层铺入锅中，不要叠放',NULL,3 FROM dish WHERE name='虎皮青椒';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,4,'用锅铲不断按压青椒使其贴锅受热，适时翻面，煎至两面出现焦黄虎皮斑',NULL,4 FROM dish WHERE name='虎皮青椒';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,5,'拨开青椒，下蒜末爆香，倒入调味汁',NULL,5 FROM dish WHERE name='虎皮青椒';
INSERT INTO dish_step(dish_id,seq,text,images,sort_order) SELECT id,6,'大火翻炒30秒，使汤汁浓稠挂在青椒上，出锅装盘',NULL,6 FROM dish WHERE name='虎皮青椒';

-- ============ 菜品-字典关联（category/cuisine/tag） ============
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,8,'category' FROM dish WHERE name='红烧肉';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,1,'cuisine' FROM dish WHERE name='红烧肉';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,4,'tag' FROM dish WHERE name='红烧肉';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,6,'tag' FROM dish WHERE name='红烧肉';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,8,'category' FROM dish WHERE name='宫保鸡丁';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,2,'cuisine' FROM dish WHERE name='宫保鸡丁';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,4,'tag' FROM dish WHERE name='宫保鸡丁';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,6,'tag' FROM dish WHERE name='宫保鸡丁';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,8,'category' FROM dish WHERE name='麻婆豆腐';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,2,'cuisine' FROM dish WHERE name='麻婆豆腐';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,6,'tag' FROM dish WHERE name='麻婆豆腐';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,8,'category' FROM dish WHERE name='糖醋排骨';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,1,'cuisine' FROM dish WHERE name='糖醋排骨';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,4,'tag' FROM dish WHERE name='糖醋排骨';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,6,'tag' FROM dish WHERE name='糖醋排骨';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,8,'category' FROM dish WHERE name='可乐鸡翅';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,1,'cuisine' FROM dish WHERE name='可乐鸡翅';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,4,'tag' FROM dish WHERE name='可乐鸡翅';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,6,'tag' FROM dish WHERE name='可乐鸡翅';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,8,'category' FROM dish WHERE name='鱼香肉丝';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,2,'cuisine' FROM dish WHERE name='鱼香肉丝';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,4,'tag' FROM dish WHERE name='鱼香肉丝';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,6,'tag' FROM dish WHERE name='鱼香肉丝';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,8,'category' FROM dish WHERE name='清蒸鲈鱼';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,3,'cuisine' FROM dish WHERE name='清蒸鲈鱼';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,7,'tag' FROM dish WHERE name='清蒸鲈鱼';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,10,'category' FROM dish WHERE name='西红柿鸡蛋汤';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,1,'cuisine' FROM dish WHERE name='西红柿鸡蛋汤';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,5,'tag' FROM dish WHERE name='西红柿鸡蛋汤';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,7,'tag' FROM dish WHERE name='西红柿鸡蛋汤';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,10,'category' FROM dish WHERE name='紫菜蛋花汤';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,1,'cuisine' FROM dish WHERE name='紫菜蛋花汤';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,5,'tag' FROM dish WHERE name='紫菜蛋花汤';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,7,'tag' FROM dish WHERE name='紫菜蛋花汤';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,8,'category' FROM dish WHERE name='虎皮青椒';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,2,'cuisine' FROM dish WHERE name='虎皮青椒';
INSERT INTO dish_dict(dish_id,dict_id,rel_type) SELECT id,6,'tag' FROM dish WHERE name='虎皮青椒';

-- ============ 菜品-食材用量 ============
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,350 FROM dish d,ingredient i WHERE d.name='红烧肉' AND i.name='五花肉';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='红烧肉' AND i.name='冰糖';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='红烧肉' AND i.name='酱油(生抽)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='红烧肉' AND i.name='酱油(老抽)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='红烧肉' AND i.name='料酒';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='红烧肉' AND i.name='生姜';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='红烧肉' AND i.name='大葱';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,5 FROM dish d,ingredient i WHERE d.name='红烧肉' AND i.name='食用油';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,2 FROM dish d,ingredient i WHERE d.name='红烧肉' AND i.name='食盐';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,350 FROM dish d,ingredient i WHERE d.name='宫保鸡丁' AND i.name='鸡胸肉';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,50 FROM dish d,ingredient i WHERE d.name='宫保鸡丁' AND i.name='花生';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,80 FROM dish d,ingredient i WHERE d.name='宫保鸡丁' AND i.name='大葱';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,50 FROM dish d,ingredient i WHERE d.name='宫保鸡丁' AND i.name='青椒';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='宫保鸡丁' AND i.name='生姜';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='宫保鸡丁' AND i.name='大蒜';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,20 FROM dish d,ingredient i WHERE d.name='宫保鸡丁' AND i.name='酱油(生抽)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='宫保鸡丁' AND i.name='醋';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='宫保鸡丁' AND i.name='白糖';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='宫保鸡丁' AND i.name='料酒';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='宫保鸡丁' AND i.name='淀粉';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,20 FROM dish d,ingredient i WHERE d.name='宫保鸡丁' AND i.name='食用油';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,2 FROM dish d,ingredient i WHERE d.name='宫保鸡丁' AND i.name='食盐';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,400 FROM dish d,ingredient i WHERE d.name='麻婆豆腐' AND i.name='豆腐(嫩)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,80 FROM dish d,ingredient i WHERE d.name='麻婆豆腐' AND i.name='猪肉(瘦)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,20 FROM dish d,ingredient i WHERE d.name='麻婆豆腐' AND i.name='豆瓣酱';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='麻婆豆腐' AND i.name='大蒜';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='麻婆豆腐' AND i.name='生姜';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='麻婆豆腐' AND i.name='酱油(生抽)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='麻婆豆腐' AND i.name='淀粉';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='麻婆豆腐' AND i.name='食用油';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,2 FROM dish d,ingredient i WHERE d.name='麻婆豆腐' AND i.name='食盐';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,500 FROM dish d,ingredient i WHERE d.name='糖醋排骨' AND i.name='排骨';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,40 FROM dish d,ingredient i WHERE d.name='糖醋排骨' AND i.name='白糖';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,25 FROM dish d,ingredient i WHERE d.name='糖醋排骨' AND i.name='醋';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='糖醋排骨' AND i.name='酱油(生抽)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,5 FROM dish d,ingredient i WHERE d.name='糖醋排骨' AND i.name='酱油(老抽)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='糖醋排骨' AND i.name='料酒';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='糖醋排骨' AND i.name='生姜';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='糖醋排骨' AND i.name='大葱';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,20 FROM dish d,ingredient i WHERE d.name='糖醋排骨' AND i.name='食用油';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='糖醋排骨' AND i.name='淀粉';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,2 FROM dish d,ingredient i WHERE d.name='糖醋排骨' AND i.name='食盐';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,400 FROM dish d,ingredient i WHERE d.name='可乐鸡翅' AND i.name='鸡翅';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,300 FROM dish d,ingredient i WHERE d.name='可乐鸡翅' AND i.name='可乐';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='可乐鸡翅' AND i.name='酱油(生抽)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,3 FROM dish d,ingredient i WHERE d.name='可乐鸡翅' AND i.name='酱油(老抽)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='可乐鸡翅' AND i.name='白糖';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='可乐鸡翅' AND i.name='料酒';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='可乐鸡翅' AND i.name='生姜';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,5 FROM dish d,ingredient i WHERE d.name='可乐鸡翅' AND i.name='食用油';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,2 FROM dish d,ingredient i WHERE d.name='可乐鸡翅' AND i.name='食盐';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,200 FROM dish d,ingredient i WHERE d.name='鱼香肉丝' AND i.name='猪肉(瘦)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,100 FROM dish d,ingredient i WHERE d.name='鱼香肉丝' AND i.name='胡萝卜';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,100 FROM dish d,ingredient i WHERE d.name='鱼香肉丝' AND i.name='青椒';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='鱼香肉丝' AND i.name='木耳(干)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='鱼香肉丝' AND i.name='豆瓣酱';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='鱼香肉丝' AND i.name='酱油(生抽)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='鱼香肉丝' AND i.name='醋';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='鱼香肉丝' AND i.name='白糖';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='鱼香肉丝' AND i.name='料酒';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='鱼香肉丝' AND i.name='淀粉';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='鱼香肉丝' AND i.name='大葱';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='鱼香肉丝' AND i.name='生姜';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='鱼香肉丝' AND i.name='大蒜';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,20 FROM dish d,ingredient i WHERE d.name='鱼香肉丝' AND i.name='食用油';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,2 FROM dish d,ingredient i WHERE d.name='鱼香肉丝' AND i.name='食盐';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,400 FROM dish d,ingredient i WHERE d.name='清蒸鲈鱼' AND i.name='鲈鱼';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,30 FROM dish d,ingredient i WHERE d.name='清蒸鲈鱼' AND i.name='大葱';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,20 FROM dish d,ingredient i WHERE d.name='清蒸鲈鱼' AND i.name='生姜';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='清蒸鲈鱼' AND i.name='酱油(生抽)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='清蒸鲈鱼' AND i.name='料酒';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='清蒸鲈鱼' AND i.name='食用油';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,5 FROM dish d,ingredient i WHERE d.name='清蒸鲈鱼' AND i.name='食盐';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,200 FROM dish d,ingredient i WHERE d.name='西红柿鸡蛋汤' AND i.name='番茄';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,100 FROM dish d,ingredient i WHERE d.name='西红柿鸡蛋汤' AND i.name='鸡蛋';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,5 FROM dish d,ingredient i WHERE d.name='西红柿鸡蛋汤' AND i.name='大葱';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='西红柿鸡蛋汤' AND i.name='食用油';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,3 FROM dish d,ingredient i WHERE d.name='西红柿鸡蛋汤' AND i.name='食盐';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,10 FROM dish d,ingredient i WHERE d.name='紫菜蛋花汤' AND i.name='紫菜(干)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,100 FROM dish d,ingredient i WHERE d.name='紫菜蛋花汤' AND i.name='鸡蛋';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,5 FROM dish d,ingredient i WHERE d.name='紫菜蛋花汤' AND i.name='大葱';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,5 FROM dish d,ingredient i WHERE d.name='紫菜蛋花汤' AND i.name='食用油';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,2 FROM dish d,ingredient i WHERE d.name='紫菜蛋花汤' AND i.name='食盐';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,250 FROM dish d,ingredient i WHERE d.name='虎皮青椒' AND i.name='青椒';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='虎皮青椒' AND i.name='大蒜';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='虎皮青椒' AND i.name='酱油(生抽)';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='虎皮青椒' AND i.name='醋';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,15 FROM dish d,ingredient i WHERE d.name='虎皮青椒' AND i.name='白糖';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,20 FROM dish d,ingredient i WHERE d.name='虎皮青椒' AND i.name='食用油';
INSERT INTO dish_ingredient(dish_id,ingredient_id,amount) SELECT d.id,i.id,3 FROM dish d,ingredient i WHERE d.name='虎皮青椒' AND i.name='食盐';

-- ============ 完成 ============
-- 新增食材：21 个
-- 新增菜品：10 道
-- 总步骤：58 步
