-- V32: 成员健康档案加 goal + activityLevel，用于每日饮食营养目标计算
ALTER TABLE member ADD COLUMN goal VARCHAR(16) DEFAULT NULL COMMENT '体控目标: MAINTAIN/LOSE/GAIN';
ALTER TABLE member ADD COLUMN activity_level VARCHAR(16) DEFAULT NULL COMMENT '活动水平: SEDENTARY/LIGHT/MODERATE/ACTIVE';
