server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # API 反代到后端（context-path=/gudu）
    location /gudu/ {
        proxy_pass http://menu-api:8080/gudu/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 50m;
    }

    # SPA 回退
    location / {
        try_files $uri $uri/ /index.html;
    }
}
